[build-system]
requires = [
	    "flit_core >=2,<4",
	    "pandas"	
	   ]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "ie_bike_model"
author = "Group 5"
author-email = "bibake@student.ie.edu"

[tool.flit.metadata.requires-extra]
dev = [
    "pytest"
]
